name: Update Site Branch

on:
  push:
    branches:
      - main

jobs:
  update-site-branch:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Generate zip files and index files
      run: |
        generate_index() {
            local dir="$1"
            local rel_path="${dir#$GITHUB_WORKSPACE}"
            local display_path="/${rel_path#/}"
            local index_file="$dir/index.html"
            
            echo "<!DOCTYPE HTML>
        <html lang=\"en\">
        <head>
        <meta charset=\"utf-8\">
        <title>Directory listing for $display_path</title>
        </head>
        <body>
        <h1>Directory listing for $display_path</h1>
        <hr>
        <ul>" > "$index_file"

            for item in "$dir"/*; do
                local item_name=$(basename "$item")
                if [[ "$item_name" != .* && "$item_name" != *.html ]]; then
                    if [ -d "$item" ]; then
                        echo "<li><a href=\"$item_name/\">$item_name/</a></li>" >> "$index_file"
                    else
                        echo "<li><a href=\"$item_name\">$item_name</a></li>" >> "$index_file"
                    fi
                fi
            done

            echo "</ul>
        <hr>
        </body>
        </html>" >> "$index_file"

            echo "Generated index.html for $display_path"
        }

        create_zip() {
            local dir="$1"
            local zip_name="$2"
            zip -j "$dir/$zip_name" "$dir"/*
            echo "Created $zip_name in $dir"
        }

        process_directory() {
            local dir="$1"
            local depth="$2"
            
            if [[ "$(basename "$dir")" == .* ]]; then
                return
            fi
            
            # Create zip file for folders one level below root
            if [ "$depth" -eq 1 ]; then
                local folder_name=$(basename "$dir")
                create_zip "$dir" "$folder_name.zip"
            fi
            
            # Create zip file for 'eng' folders at depth 2
            if [ "$depth" -eq 2 ] && [ "$(basename "$dir")" = "eng" ]; then
                local parent_folder=$(basename "$(dirname "$dir")")
                create_zip "$dir" "$parent_folder - eng.zip"
            fi
            
            # Generate index after creating zip files
            generate_index "$dir"
            
            for subdir in "$dir"*/; do
                if [ -d "$subdir" ] && [[ "$(basename "$subdir")" != .* ]]; then
                    process_directory "$subdir" $((depth + 1))
                fi
            done
        }

        process_directory "$GITHUB_WORKSPACE" 0

    - name: Update site branch
      run: |
        # Add all changes
        git add .

        # Commit the changes
        git commit -m "Update site with latest zip archives and index files"

        # Force push the site branch
        git push -u -f origin main:site